spring:
  batch:
    job:
      enabled: true
    initialize-schema: always
  datasource:
#   url: jdbc:postgresql://localhost/collector_collaborator
    url: jdbc:postgresql://localhost/collecte_collaborateur
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

      # datasource :
      #  url : jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
      #    username : sa
      #   password :
      #   driver-class-name : org.h2.Driver
      #h2 :
      #console :
    # enabled: true

